(() => {
  const CATEGORY_RULES = [
    {
      category: "Study",
      domains: [
        "developer.mozilla.org",
        "learn.microsoft.com",
        "docs.microsoft.com",
        "docs.python.org",
        "docs.oracle.com",
        "docs.rust-lang.org",
        "docs.swift.org",
        "docs.flutter.dev",
        "docs.docker.com",
        "kubernetes.io",
        "stackoverflow.com",
        "stackexchange.com",
        "github.com",
        "gitlab.com",
        "bitbucket.org",
        "wikipedia.org",
        "w3schools.com",
        "khanacademy.org",
        "coursera.org",
        "edx.org",
        "udemy.com",
        "pluralsight.com",
        "codecademy.com",
        "freecodecamp.org",
        "brilliant.org",
        "skillshare.com",
        "lynda.com",
        "scholar.google.com",
        "arxiv.org",
        "jstor.org",
        "researchgate.net",
        "mit.edu",
        "stanford.edu",
        "medium.com",
        "dev.to",
        "hashnode.dev",
      ],
    },
    {
      category: "Social",
      domains: [
        "twitter.com",
        "x.com",
        "facebook.com",
        "instagram.com",
        "tiktok.com",
        "reddit.com",
        "discord.com",
        "linkedin.com",
        "threads.net",
        "snapchat.com",
        "pinterest.com",
        "tumblr.com",
        "mastodon.social",
        "bsky.app",
        "quora.com",
        "whatsapp.com",
        "telegram.org",
        "slack.com",
      ],
    },
    {
      category: "Video",
      domains: [
        "youtube.com",
        "youtu.be",
        "twitch.tv",
        "vimeo.com",
        "dailymotion.com",
        "netflix.com",
        "hulu.com",
        "primevideo.com",
        "disneyplus.com",
        "crunchyroll.com",
        "peacocktv.com",
        "max.com",
        "paramountplus.com",
        "appletv.apple.com",
        "plex.tv",
      ],
    },
    {
      category: "Shopping",
      domains: [
        "amazon.com",
        "ebay.com",
        "etsy.com",
        "aliexpress.com",
        "walmart.com",
        "target.com",
        "bestbuy.com",
        "shopify.com",
        "wayfair.com",
        "newegg.com",
        "costco.com",
        "homedepot.com",
        "ikea.com",
        "shein.com",
        "temu.com",
        "wish.com",
      ],
    },
    {
      category: "News",
      domains: [
        "news.ycombinator.com",
        "news.google.com",
        "nytimes.com",
        "bbc.com",
        "bbc.co.uk",
        "cnn.com",
        "reuters.com",
        "theguardian.com",
        "washingtonpost.com",
        "bloomberg.com",
        "apnews.com",
        "arstechnica.com",
        "theverge.com",
        "wired.com",
        "techcrunch.com",
        "engadget.com",
        "vice.com",
        "vox.com",
        "theatlantic.com",
      ],
    },
    {
      category: "Gaming",
      domains: [
        "store.steampowered.com",
        "steampowered.com",
        "epicgames.com",
        "gog.com",
        "itch.io",
        "roblox.com",
        "minecraft.net",
        "ea.com",
        "playstation.com",
        "xbox.com",
        "nintendo.com",
        "ign.com",
        "gamespot.com",
        "kotaku.com",
        "polygon.com",
        "pcgamer.com",
      ],
    },
    {
      category: "Music",
      domains: [
        "open.spotify.com",
        "spotify.com",
        "music.apple.com",
        "music.youtube.com",
        "soundcloud.com",
        "bandcamp.com",
        "tidal.com",
        "deezer.com",
        "pandora.com",
        "last.fm",
        "genius.com",
      ],
    },
    {
      category: "Finance",
      domains: [
        "robinhood.com",
        "coinbase.com",
        "binance.com",
        "finance.yahoo.com",
        "marketwatch.com",
        "cnbc.com",
        "investopedia.com",
        "mint.com",
        "chase.com",
        "bankofamerica.com",
        "paypal.com",
        "venmo.com",
        "wise.com",
        "fidelity.com",
      ],
    },
    {
      category: "Health",
      domains: [
        "webmd.com",
        "mayoclinic.org",
        "healthline.com",
        "nih.gov",
        "cdc.gov",
        "who.int",
        "medlineplus.gov",
        "drugs.com",
        "myfitnesspal.com",
        "strava.com",
        "fitbit.com",
        "calm.com",
        "headspace.com",
      ],
    },
    {
      category: "Dev Tools",
      domains: [
        "vercel.com",
        "netlify.com",
        "heroku.com",
        "digitalocean.com",
        "aws.amazon.com",
        "console.cloud.google.com",
        "portal.azure.com",
        "firebase.google.com",
        "supabase.com",
        "cloudflare.com",
        "npmjs.com",
        "pypi.org",
        "crates.io",
        "hub.docker.com",
        "railway.app",
        "render.com",
        "codepen.io",
        "codesandbox.io",
        "replit.com",
        "jsfiddle.net",
      ],
    },
    {
      category: "AI & ML",
      domains: [
        "chat.openai.com",
        "openai.com",
        "claude.ai",
        "anthropic.com",
        "bard.google.com",
        "gemini.google.com",
        "copilot.microsoft.com",
        "huggingface.co",
        "kaggle.com",
        "midjourney.com",
        "stability.ai",
        "perplexity.ai",
        "poe.com",
        "character.ai",
        "replicate.com",
      ],
    },
  ];

  const CATEGORY_MULTIPLIERS = {
    Study: 0.7,
    "Dev Tools": 0.75,
    "AI & ML": 0.8,
    Health: 0.8,
    Finance: 0.85,
    News: 0.85,
    Music: 0.95,
    Shopping: 1.15,
    Gaming: 1.25,
    Social: 1.3,
    Video: 1.4,
    Random: 1.0,
  };

  const CATEGORY_LIST = Object.keys(CATEGORY_MULTIPLIERS);

  globalThis.IRHTCategories = {
    CATEGORY_RULES,
    CATEGORY_MULTIPLIERS,
    CATEGORY_LIST,
  };
})();
